export const ODOT_LEADS = [
  {
    "id": "odot_2kg_contractors",
    "name": "2Kg Contractors",
    "city": "Portland, OR",
    "phone": "(503)489-2020",
    "email": "jill@2kgcontractors.com",
    "address": "4917 NE 185TH DR",
    "niche": "Buildings",
    "workClasses": "BLD1, EART, MHA, PCP, REIN",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_3_kings_environmental_inc",
    "name": "3 Kings Environmental Inc",
    "city": "Battle Ground, WA",
    "phone": "(360)666-5464",
    "email": "kwarmuth@3kingsinc.com",
    "address": "PO BOX 280",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, REIN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_4s_signs_llc",
    "name": "4S Signs Llc",
    "city": "Albany, OR",
    "phone": "541-928-5858",
    "email": "buck@foresssign.com",
    "address": "30255 HWY 34",
    "niche": "Signage",
    "workClasses": "SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_7_peaks_paving_llc",
    "name": "7 Peaks Paving Llc",
    "city": "Bend, OR",
    "phone": "(541)408-1302",
    "email": "markg@7peakspaving.com",
    "address": "6005 CINDER BUTTE RD",
    "niche": "Paving",
    "workClasses": "AB, ACP",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_aaken_corporation_electric",
    "name": "Aaken Corporation Electric",
    "city": "Bend, OR",
    "phone": "(541)410-8286",
    "email": "aaron@aakencorp.com",
    "address": "1260 NE FIRST ST",
    "niche": "Electrical",
    "workClasses": "EART, ELEC, SIGN",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_ab_hinderlie_construction",
    "name": "Ab Hinderlie Construction",
    "city": "Lebanon, OR",
    "phone": "(541)409-6632",
    "email": "abhinderlieconstruction@gmail.com",
    "address": "1164 W OAK ST",
    "niche": "Buildings",
    "workClasses": "AB, BLD1, EART",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_adams_quality_fence_inc",
    "name": "Adams Quality Fence Inc",
    "city": "Milwaukie, OR",
    "phone": "(503)683-1271",
    "email": "info@adamsqualityfence.com",
    "address": "14829 SE MARIAN ST",
    "niche": "General Contractor",
    "workClasses": "MHA",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_andres_landscape",
    "name": "Andres Landscape",
    "city": "Molalla, OR",
    "phone": "(503)632-3366",
    "email": "noah@andreslandscapellc.com",
    "address": "175 GRANGE AVE",
    "niche": "Landscaping",
    "workClasses": "LS",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_apex_mechanical_llc",
    "name": "Apex Mechanical Llc",
    "city": "Battleground, WA",
    "phone": "360-666-8735",
    "email": "john@apexmechanical.org",
    "address": "1507 SE EATON BLVD",
    "niche": "Buildings",
    "workClasses": "BLD1",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_aquatic_contracting_llc",
    "name": "Aquatic Contracting Llc",
    "city": "Portland, OR",
    "phone": "503-490-2933",
    "email": "mike@aquatic-con.com",
    "address": "12950 NW MARINA WAY",
    "niche": "Landscaping",
    "workClasses": "EART, LS, OTH1, REIN",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_armadillo_boring_inc",
    "name": "Armadillo Boring Inc",
    "city": "Salem, OR",
    "phone": "(503)588-8050",
    "email": "tim@armadilloboring.com",
    "address": "2420 MCGILCHRIST ST SE",
    "niche": "Excavation",
    "workClasses": "EART, OTH1",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_auden_construction_llc",
    "name": "Auden Construction Llc",
    "city": "Salem, OR",
    "phone": "(971)304-5842",
    "email": "rogers@audenconstruction.com",
    "address": "2104 TEAKWOOD AVE NW",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_benchmark_contracting_inc",
    "name": "Benchmark Contracting Inc",
    "city": "Lake Oswego, OR",
    "phone": "(503)780-9760",
    "email": "kelly@benchmark-pdx.com",
    "address": "5809 JEAN ROAD",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, OTH1, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_bergerson_construction_inc",
    "name": "Bergerson Construction Inc",
    "city": "Astoria, OR",
    "phone": "(503)325-7130",
    "email": "estimating@bergerson-const.com",
    "address": "300 RAILROAD AVE",
    "niche": "Excavation",
    "workClasses": "EART, OTH1, REIN",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_big_river_excavating",
    "name": "Big River Excavating",
    "city": "Astoria, OR",
    "phone": "(503)338-3878",
    "email": "tewing@bigrivercompanies.com",
    "address": "35064 HIGHWAY 101 BUSINESS ASTORIA",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, MHA, OTH1, PAVE, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_bill_erickson_heavy_const_inc",
    "name": "Bill Erickson Heavy Const Inc",
    "city": "Oregon City, OR",
    "phone": "(503)655-3478",
    "email": "billerickson@comcast.net",
    "address": "15720 HARLEY AVE",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_bdl_plumbing_llc",
    "name": "Bdl Plumbing Llc",
    "city": "Corbett, OR",
    "phone": "503-351-3903",
    "email": "bdlanter@gmail.com",
    "address": "301 NE CURTIS",
    "niche": "Buildings",
    "workClasses": "AB, AC, BLD1, MHA, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_blue_spruce_builders_inc",
    "name": "Blue Spruce Builders Inc",
    "city": "Dallas, OR",
    "phone": "(503)930-9888",
    "email": "rich@bluesprucebuilders.com",
    "address": "4600 PERRYDALE RD",
    "niche": "Buildings",
    "workClasses": "BLD1",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_bob_mcewan_construction_inc",
    "name": "Bob Mcewan Construction Inc",
    "city": "Seaside, OR",
    "phone": "503-440-0223",
    "email": "mmcewan3569@gmail.com",
    "address": "34154 HWY 26",
    "niche": "Excavation",
    "workClasses": "EART",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_braun_construction_&_design_ll",
    "name": "Braun Construction & Design Llc",
    "city": "Wilsonville, OR",
    "phone": "(503)638-6406",
    "email": "jeanie@braunc.com",
    "address": "24805 SW GAGE RD",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_brown_contracting_inc",
    "name": "Brown Contracting Inc",
    "city": "Eugene, OR",
    "phone": "(541)338-9345",
    "email": "sean@browncontracting.net",
    "address": "29534 AIRPORT RD",
    "niche": "Electrical",
    "workClasses": "AB, ACP, BLD1, EART, ELEC, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_canby_excavating_inc",
    "name": "Canby Excavating Inc",
    "city": "Aurora, OR",
    "phone": "(503)266-2792",
    "email": "benb@canbyex.com",
    "address": "25361 S HWY 99E",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, PAVE, REIN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_carter_&_company_inc",
    "name": "Carter & Company Inc",
    "city": "Salem, OR",
    "phone": "(503)371-4582",
    "email": "colby@carter-co.com",
    "address": "5050 36TH AVE SE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_coral_construction_co",
    "name": "Coral Construction Co",
    "city": "Sherwood, OR",
    "phone": "(503)682-2252",
    "email": "marcroberts@coralconstruction.com",
    "address": "10780 SW CLUTTER RD",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_eagle_elsner_inc",
    "name": "Eagle Elsner Inc",
    "city": "Sherwood, OR",
    "phone": "(503)628-1137",
    "email": "curtis@eagle-elsner.com",
    "address": "17400 SW HILLSBORO HWY",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, PAVE, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_emery_&_sons_construction",
    "name": "Emery & Sons Construction",
    "city": "Salem, OR",
    "phone": "(503)588-7575",
    "email": "bids@emeryandsons.com",
    "address": "3841 FAIRVIEW INDUSTRIAL DR SE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, BLD1, EART, ELEC, LS, MHA, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_coral_construction_co",
    "name": "Coral Construction Co",
    "city": "Sherwood, OR",
    "phone": "(503)682-2252",
    "email": "marcroberts@coralconstruction.com",
    "address": "10780 SW CLUTTER RD",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_gelco_construction_co",
    "name": "Gelco Construction Co",
    "city": "Salem, OR",
    "phone": "(503)364-2638",
    "email": "tomj@gelcoconstruction.com",
    "address": "1745 SALEM INDUSTRIAL DR NE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_hp_civil_inc",
    "name": "Hp Civil Inc",
    "city": "Salem, OR",
    "phone": "(503)769-2466",
    "email": "estimating@hpcivil.com",
    "address": "8795 AUMSVILLE HWY SE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_hoffman_construction_co",
    "name": "Hoffman Construction Co",
    "city": "Portland, OR",
    "phone": "(503)221-8811",
    "email": "christyn-halliday@hoffmancorp.com",
    "address": "805 SW BROADWAY STE 2100",
    "niche": "Buildings",
    "workClasses": "AB, ACP, BLD1, PCP, REIN",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_hoss_paving_inc",
    "name": "Hoss Paving Inc",
    "city": "North Plains, OR",
    "phone": "(503)647-1220",
    "email": "hosspaving@msn.com",
    "address": "32590 NW COMMERCIAL ST",
    "niche": "Excavation",
    "workClasses": "AB, ACP, EART, MHA, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_interlaken,_inc.",
    "name": "Interlaken, Inc.",
    "city": "Gresham, OR",
    "phone": "(503)674-7460",
    "email": "andy@interlaken-inc.com",
    "address": "2026 NW BIRDSDALE AVE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_iron_horse_llc",
    "name": "Iron Horse Llc",
    "city": "Fairview, OR",
    "phone": "5036740980",
    "email": "brandon@ironhorsellc.com",
    "address": "5501 NE 223RD AVE BLDG D",
    "niche": "Excavation",
    "workClasses": "EART",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_joe_mallory",
    "name": "Joe Mallory",
    "city": "Forest Grove, OR",
    "phone": "(503)648-9310",
    "email": "joe@subcomex.com",
    "address": "2850 TAYLOR WAY",
    "niche": "Landscaping",
    "workClasses": "AB, ACP, EART, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_jse_inc_dba_jim_smith_excavati",
    "name": "Jse Inc Dba Jim Smith Excavating Inc",
    "city": "Clackamas, OR",
    "phone": "(503)557-7470",
    "email": "rsmith@jimsmithexcavating.com",
    "address": "17316 SE WILDE RD",
    "niche": "Landscaping",
    "workClasses": "AB, ACP, EART, LS, MHA, OTH1, REIN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_k_&_e_excavating_inc",
    "name": "K & E Excavating Inc",
    "city": "Salem, OR",
    "phone": "(503)399-4833",
    "email": "chad@keex.net",
    "address": "3871 LANGLEY ST SE",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, EART, ELEC, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_ken_leahy_construction,_inc",
    "name": "Ken Leahy Construction, Inc",
    "city": "Cornelius, OR",
    "phone": "(503)357-2193",
    "email": "sladel@kenleahy.com",
    "address": "915 S 12TH AVENUE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_kerr_contractors_oregon_llc",
    "name": "Kerr Contractors Oregon Llc",
    "city": "Woodburn, OR",
    "phone": "(971)216-0050",
    "email": "estimating@kerrcontractors.com",
    "address": "395 SHENANDOAH LN NE",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_kodiak_pacific_construction",
    "name": "Kodiak Pacific Construction",
    "city": "Sherwood, OR",
    "phone": "(503)783-4300",
    "email": "tims@kodiakco.com",
    "address": "10940 SW CLUTTER RD",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, MHA, OTH1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_landis_&_landis_construction_l",
    "name": "Landis & Landis Construction Llc",
    "city": "Canby, OR",
    "phone": "(503)466-9043",
    "email": "mlandis@llconstruction.com",
    "address": "193 NE 3RD AVE",
    "niche": "Buildings",
    "workClasses": "AB, ACP, BLD1, EART, MHA, PCP, REIN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_lawson_corp",
    "name": "Lawson Corp",
    "city": "Carlton, OR",
    "phone": "(503)852-0035",
    "email": "bids@larson-corp.com",
    "address": "230 S PARK ST",
    "niche": "Landscaping",
    "workClasses": "AB, ACP, EART, LS, MHA, PAVE, REIN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_legacy_contracting_inc",
    "name": "Legacy Contracting Inc",
    "city": "Stayton, OR",
    "phone": "(503)749-1818",
    "email": "bids@legacycontractinginc.com",
    "address": "41850 KINGSTON-JORDAN RD",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_ml_houck_construction_co_inc",
    "name": "Ml Houck Construction Co Inc",
    "city": "Salem, OR",
    "phone": "(503)463-7177",
    "email": "sarah@houckco.com",
    "address": "4444 22ND AVE NE",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, EART, ELEC, LS, MHA, PAVE, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_moore_excavation_inc",
    "name": "Moore Excavation Inc",
    "city": "Fairview, OR",
    "phone": "(503)674-0948",
    "email": "bids@themeigroup.com",
    "address": "5501 NE 223RD AVE",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_north_santiam_paving_co",
    "name": "North Santiam Paving Co",
    "city": "Stayton, OR",
    "phone": "(503)769-3436",
    "email": "quotes@nspor.com",
    "address": "41203 KINGSTON-LYONS DR",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_northwest_earthmovers_inc",
    "name": "Northwest Earthmovers Inc",
    "city": "Sherwood, OR",
    "phone": "(503)625-3100",
    "email": "jaredhargens@nwearthmovers.com",
    "address": "13600 SW GALBREATH DR",
    "niche": "Electrical",
    "workClasses": "AB, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_paul_brothers_inc",
    "name": "Paul Brothers Inc",
    "city": "Boring, OR",
    "phone": "(503)663-1220",
    "email": "ppaul@paulbrothersinc.com",
    "address": "8601 SE REVENUE RD",
    "niche": "Landscaping",
    "workClasses": "AB, ACP, BLD1, EART, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_pihl_inc",
    "name": "Pihl Inc",
    "city": "Banks, OR",
    "phone": "(503)330-2103",
    "email": "todd.pittman@pihl-inc.com",
    "address": "41660 NW SUNSET HWY",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, OTH1, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_r_&_r_general_contractors_inc",
    "name": "R & R General Contractors Inc",
    "city": "Salem, OR",
    "phone": "(503)586-0388",
    "email": "jrodriguez@rrgcinc.net",
    "address": "1740 22ND ST SE",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_r&g_excavating_inc",
    "name": "R&G Excavating Inc",
    "city": "Scio, OR",
    "phone": "(503)394-2190",
    "email": "admin@rgexcavating.com",
    "address": "39300 MONTGOMERY DR",
    "niche": "Painting",
    "workClasses": "AB, ACP, BLD1, EART, MHA, PAI1, REIN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_roy_houck_construction_llc",
    "name": "Roy Houck Construction Llc",
    "city": "Salem, OR",
    "phone": "(503)463-7177",
    "email": "sara@houckco.com",
    "address": "4444 22ND AVE NE",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, EART, ELEC, LS, MHA, PAVE, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_s_&_w_underground",
    "name": "S & W Underground",
    "city": "Troutdale, OR",
    "phone": "(503)853-5454",
    "email": "travis@sandwunderground.com",
    "address": "2360 NW MARINE DR",
    "niche": "Electrical",
    "workClasses": "AB, ACP, BLD1, EART, ELEC, LS, MHA, PAVE, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_s-2_contractors_inc",
    "name": "S-2 Contractors Inc",
    "city": "Aurora, OR",
    "phone": "(503)651-4000",
    "email": "krobitsch@s2contractorsinc.com",
    "address": "6860 S ANDERSON RD",
    "niche": "Landscaping",
    "workClasses": "AB, ACP, EART, LS, MHA, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_the_saunders_company_inc",
    "name": "The Saunders Company Inc",
    "city": "Newberg, OR",
    "phone": "(503)537-9950",
    "email": "jeff@thesaunderscompany.net",
    "address": "701 E THIRD STREET",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, BLD1, EART, ELEC, LS, MHA, PAI1, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_tice_electric_co",
    "name": "Tice Electric Co",
    "city": "Portland, OR",
    "phone": "503-936-1961",
    "email": "joes@ticeelectric.com",
    "address": "5405 N LAGOON AVE",
    "niche": "Electrical",
    "workClasses": "ELEC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_town_&_country_fence_co_of_ore",
    "name": "Town & Country Fence Co Of Oregon",
    "city": "Clackamas, OR",
    "phone": "(503)515-2021",
    "email": "david@tcfence.us",
    "address": "8810 SE HERBERT CT",
    "niche": "General Contractor",
    "workClasses": "MHA",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_tft_construction_inc",
    "name": "Tft Construction Inc",
    "city": "Scappoose, OR",
    "phone": "(503)543-7979",
    "email": "tom@tftconstruction.net",
    "address": "53990 WEST LANE RD",
    "niche": "Electrical",
    "workClasses": "AB, AC, ACP, EART, ELEC, LS, MHA, PAVE, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_todd_construction_inc",
    "name": "Todd Construction Inc",
    "city": "Tigard, OR",
    "phone": "(503)620-7652",
    "email": "bschafer@toddconstruction.com",
    "address": "18407 SW BOONES FERRY RD",
    "niche": "Landscaping",
    "workClasses": "ACP, BLD1, EART, LS, PAI1, PAVE, PCP, REIN, SIGN",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_titan_utilities_llc",
    "name": "Titan Utilities Llc",
    "city": "Beaverton, OR",
    "phone": "(503)706-8288",
    "email": "john@titanutilities.net",
    "address": "11562 SW 175TH AVE",
    "niche": "Excavation",
    "workClasses": "EART, OTH1",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_willamette_fence_co_inc",
    "name": "Willamette Fence Co Inc",
    "city": "Portland, OR",
    "phone": "(503)285-2761",
    "email": "chris@willamettefence.com",
    "address": "11304 NE MARX ST",
    "niche": "General Contractor",
    "workClasses": "MHA",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_willamette_valley_excavating_l",
    "name": "Willamette Valley Excavating Llc",
    "city": "Albany, OR",
    "phone": "(503)932-7012",
    "email": "brad@wv-excavating.com",
    "address": "38950 MASON RD",
    "niche": "Electrical",
    "workClasses": "AB, ACP, EART, ELEC, LS, MHA, PAVE, PCP, REIN, SIGN, TTC",
    "source": "ODOT Prequalified",
    "hasEmail": true
  },
  {
    "id": "odot_woodburn_construction_cm/gc,_l",
    "name": "Woodburn Construction Cm/Gc, Llc",
    "city": "Woodburn, OR",
    "phone": "(503)981-9504",
    "email": "bert@woodburnconstruction.com",
    "address": "683 RAY J GLATT CIRCLE",
    "niche": "Buildings",
    "workClasses": "BLD1",
    "source": "ODOT Prequalified",
    "hasEmail": true
  }
];
